### PR TITLE
Add netcoredbg as tool for F# language

### PR DESCRIPTION
**Pull request by adelarsq**
Hello! This adds [netcoredbg](https://github.com/Samsung/netcoredbg) as debug tool for [F#](https://fsharp.org).

### CODE REVIEW

**Review by williamboman — COMMENTED** [review]
Cool! However that file is [not to be manually edited](https://github.com/williamboman/mason.nvim/blob/bc4e518f27db8d1d062c35501e3939b475d4e13b/lua/mason/mappings/language.lua#L1), it's automatically generated from code.

**Comment by williamboman** [comment]
@williambotman /fixup

**Comment by williamboman** [comment]
@williambotman /apply

```diff
diff --git a/lua/mason-registry/netcoredbg/init.lua b/lua/mason-registry/netcoredbg/init.lua
index 8806d5f..10a5c1a 100644
--- a/lua/mason-registry/netcoredbg/init.lua
+++ b/lua/mason-registry/netcoredbg/init.lua
@@ -8,7 +8,7 @@ return Pkg.new {
     name = "netcoredbg",
     desc = [[NetCoreDbg is a managed code debugger with MI interface for CoreCLR.]],
     homepage = "https://github.com/Samsung/netcoredbg",
-    languages = { Pkg.Lang[".NET"], Pkg.Lang["C#"] },
+    languages = { Pkg.Lang[".NET"], Pkg.Lang["C#"], Pkg.Lang["F#"] },
     categories = { Pkg.Cat.DAP },
     ---@async
     ---@param ctx InstallContext
```

**Comment by williamboman** [comment]
@williambotman /fixup

**Comment by adelarsq** [comment]
> Cool! However that file is [not to be manually edited](https://github.com/williamboman/mason.nvim/blob/bc4e518f27db8d1d062c35501e3939b475d4e13b/lua/mason/mappings/language.lua#L1), it's automatically generated from code.

@williamboman Oh thanks! Didn't know that 😮

**Pull request merged**
