### PR TITLE
feat(registry): add cppcheck linter

### LINKED ISSUE #353: [New package]: cppcheck
### Package name

cppcheck

### Package homepage

https://github.com/danmar/cppcheck

### Languages

cpp

### How is this package distributed?

It seems that we have to build this from source... (For Windows there's an msi on the release page.)

```bash
git clone --depth=1 https://github.com/danmar/cppcheck
cd cppcheck
mkdir build
cd build
cmake ..
cmake --build .
cmake install -DCMAKE_INSTALL_PREFIX=/path/to/mason/packages
```

### PR DESCRIPTION
**Pull request by VanillaBase1lb**
Add `cppcheck` to the registry.
Since there is no official binary release for Linux, using `make` to compile it, suggestions and alternatives are welcomed.

This closes #353

### CODE REVIEW

**Comment by williamboman** [comment]
@williambotman /apply

```diff
diff --git a/lua/mason-registry/cppcheck/init.lua b/lua/mason-registry/cppcheck/init.lua
index 85f70527..7a60a839 100644
--- a/lua/mason-registry/cppcheck/init.lua
+++ b/lua/mason-registry/cppcheck/init.lua
@@ -2,10 +2,14 @@ local Pkg = require "mason-core.package"
 local Optional = require "mason-core.optional"
 local git = require "mason-core.managers.git"
 local github = require "mason-core.managers.github"
+local _ = require "mason-core.functional"
 
 return Pkg.new {
     name = "cppcheck",
-    desc = [[ Cppcheck is an analysis tool for C/C++ code. It detects the types of bugs that the compilers normally fail to detect. The goal is no false positives. ]],
+    desc = _.dedent [[
+        Cppcheck is an analysis tool for C/C++ code. It detects the types of bugs that the compilers normally fail to
+        detect. The goal is no false positives.
+    ]],
     homepage = "https://cppcheck.sourceforge.io/",
     languages = { Pkg.Lang.C, Pkg.Lang["C++"] },
     categories = { Pkg.Cat.Linter },
```

**Comment by VanillaBase1lb** [comment]
I did not mean to force push, any way to undo this?

**Comment by williamboman** [comment]
> I did not mean to force push, any way to undo this?
> 
> I still have the changes in my local repository, will reopen the PR.

Ah no worries, cool :+1:. I've waited with merging this for now because I'd like to manually revise the install script and potentially harden it a bit more. Generally I try to avoid custom "low-level" install scripts due to difficulties in ensuring sufficient cross-platform support.

**Comment by williamboman** [comment]
Hey @VanillaBase1lb I've not forgotten about this PR. I have however struggled to build this on some systems but have not yet had time to look into it more closely.

**Comment by VanillaBase1lb** [comment]
No problem. Regarding not being able to build on some systems, is it an upstream(cppcheck) issue or something to do with Mason.nvim? Maybe we could help if there is more info on this.

**Comment by williamboman** [comment]
Closing this as packages are no longer added to this registry, see instead https://github.com/mason-org/mason-registry/.

**Pull request closed without merging**
