### PR TITLE
Add support for Verible LSP to CentOS

### PR DESCRIPTION
**Pull request by nikhiljha**
Verible publishes binaries for CentOS 7.9, but Mason doesn't expose them. This PR adds platform detection logic for CentOS and adds the binary name for CentOS to the Verible LSP.

Needs squash + merge-- git history unclean.

### CODE REVIEW

**Comment by williamboman** [comment]
@williambotman /apply

```diff
diff --git a/lua/mason-registry/verible/init.lua b/lua/mason-registry/verible/init.lua
index 5f2fa36..5773cf0 100644
--- a/lua/mason-registry/verible/init.lua
+++ b/lua/mason-registry/verible/init.lua
@@ -21,28 +21,33 @@ return Pkg.new {
                 local os_dist = platform.os_distribution()
                 local source = github.untarxz_release_file {
                     repo = repo,
-                    asset_file = function(release)
-                        if os_dist.id == "ubuntu" then
-                            local target_file = when(
-                                platform.arch == "x64",
-                                coalesce(
-                                    when(os_dist.version.major == 16, "verible-%s-Ubuntu-16.04-xenial-x86_64.tar.gz"),
-                                    when(os_dist.version.major == 18, "verible-%s-Ubuntu-18.04-bionic-x86_64.tar.gz"),
-                                    when(os_dist.version.major == 20, "verible-%s-Ubuntu-20.04-focal-x86_64.tar.gz"),
-                                    when(os_dist.version.major == 22, "verible-%s-Ubuntu-22.04-jammy-x86_64.tar.gz")
-                                )
-                            )
-                            return target_file and target_file:format(release)
-                        elseif os_dist.id == "centos" then
-                            local target_file = when(
-                                platform.arch == "x64",
-                                coalesce(
-                                    when(os_dist.version.major == 7, "verible-%s-CentOS-7.9.2009-Core-x86_64.tar.gz")
+                    asset_file = coalesce(
+                        when(
+                            os_dist.id == "ubuntu" and platform.arch == "x64",
+                            coalesce(
+                                when(
+                                    os_dist.version.major == 16,
+                                    _.format "verible-%s-Ubuntu-16.04-xenial-x86_64.tar.gz"
+                                ),
+                                when(
+                                    os_dist.version.major == 18,
+                                    _.format "verible-%s-Ubuntu-18.04-bionic-x86_64.tar.gz"
+                                ),
+                                when(
+                                    os_dist.version.major == 20,
+                                    _.format "verible-%s-Ubuntu-20.04-focal-x86_64.tar.gz"
+                                ),
+                                when(
+                                    os_dist.version.major == 22,
+                                    _.format "verible-%s-Ubuntu-22.04-jammy-x86_64.tar.gz"
                                 )
                             )
-                            return target_file and target_file:format(release)
-                        end
-                    end,
+                        ),
+                        when(
+                            os_dist.id == "centos" and platform.arch == "x64",
+                            coalesce(when(os_dist.version.major == 7, "verible-%s-CentOS-7.9.2009-Core-x86_64.tar.gz"))
+                        )
+                    ),
                 }
                 source.with_receipt()
                 ctx.fs:rename(("verible-%s"):format(source.release), "verible")
```

**Comment by williamboman** [comment]
@williambotman /apply

```diff
diff --git a/lua/mason-core/platform.lua b/lua/mason-core/platform.lua
index 85b1407..0ab6d5f 100644
--- a/lua/mason-core/platform.lua
+++ b/lua/mason-core/platform.lua
@@ -160,6 +160,7 @@ M.os_distribution = _.lazy(function()
         else
             return {
                 id = "linux-generic",
+                version = {}
             }
         end
     end
@@ -173,7 +174,7 @@ M.os_distribution = _.lazy(function()
                     return parse_linux_dist(result.stdout)
                 end)
                 :recover(function()
-                    return { id = "linux-generic" }
+                    return { id = "linux-generic", version = {} }
                 end)
                 :get_or_throw()
         end,
diff --git a/lua/mason-registry/verible/init.lua b/lua/mason-registry/verible/init.lua
index 5f2fa36..5773cf0 100644
--- a/lua/mason-registry/verible/init.lua
+++ b/lua/mason-registry/verible/init.lua
@@ -21,28 +21,33 @@ return Pkg.new {
                 local os_dist = platform.os_distribution()
                 local source = github.untarxz_release_file {
                     repo = repo,
-                    asset_file = function(release)
-                        if os_dist.id == "ubuntu" then
-                            local target_file = when(
-                                platform.arch == "x64",
-                                coalesce(
-                                    when(os_dist.version.major == 16, "verible-%s-Ubuntu-16.04-xenial-x86_64.tar.gz"),
-                                    when(os_dist.version.major == 18, "verible-%s-Ubuntu-18.04-bionic-x86_64.tar.gz"),
-                                    when(os_dist.version.major == 20, "verible-%s-Ubuntu-20.04-focal-x86_64.tar.gz"),
-                                    when(os_dist.version.major == 22, "verible-%s-Ubuntu-22.04-jammy-x86_64.tar.gz")
-                                )
-                            )
-                            return target_file and target_file:format(release)
-                        elseif os_dist.id == "centos" then
-                            local target_file = when(
-                                platform.arch == "x64",
-                                coalesce(
-                                    when(os_dist.version.major == 7, "verible-%s-CentOS-7.9.2009-Core-x86_64.tar.gz")
+                    asset_file = coalesce(
+                        when(
+                            os_dist.id == "ubuntu" and platform.arch == "x64",
+                            coalesce(
+                                when(
+                                    os_dist.version.major == 16,
+                                    _.format "verible-%s-Ubuntu-16.04-xenial-x86_64.tar.gz"
+                                ),
+                                when(
+                                    os_dist.version.major == 18,
+                                    _.format "verible-%s-Ubuntu-18.04-bionic-x86_64.tar.gz"
+                                ),
+                                when(
+                                    os_dist.version.major == 20,
+                                    _.format "verible-%s-Ubuntu-20.04-focal-x86_64.tar.gz"
+                                ),
+                                when(
+                                    os_dist.version.major == 22,
+                                    _.format "verible-%s-Ubuntu-22.04-jammy-x86_64.tar.gz"
                                 )
                             )
-                            return target_file and target_file:format(release)
-                        end
-                    end,
+                        ),
+                        when(
+                            os_dist.id == "centos" and platform.arch == "x64",
+                            coalesce(when(os_dist.version.major == 7, "verible-%s-CentOS-7.9.2009-Core-x86_64.tar.gz"))
+                        )
+                    ),
                 }
                 source.with_receipt()
                 ctx.fs:rename(("verible-%s"):format(source.release), "verible")
```

**Comment by williamboman** [comment]
@williambotman /apply

```diff
diff --git a/lua/mason-core/platform.lua b/lua/mason-core/platform.lua
index 85b1407..0ab6d5f 100644
--- a/lua/mason-core/platform.lua
+++ b/lua/mason-core/platform.lua
@@ -160,6 +160,7 @@ M.os_distribution = _.lazy(function()
         else
             return {
                 id = "linux-generic",
+                version = {}
             }
         end
     end
@@ -173,7 +174,7 @@ M.os_distribution = _.lazy(function()
                     return parse_linux_dist(result.stdout)
                 end)
                 :recover(function()
-                    return { id = "linux-generic" }
+                    return { id = "linux-generic", version = {} }
                 end)
                 :get_or_throw()
         end,
```

**Comment by williamboman** [comment]
@williambotman /fixup

**Comment by williamboman** [comment]
@williambotman /apply

```diff
diff --git a/lua/mason-registry/verible/init.lua b/lua/mason-registry/verible/init.lua
index 5773cf0..765cf19 100644
--- a/lua/mason-registry/verible/init.lua
+++ b/lua/mason-registry/verible/init.lua
@@ -45,7 +45,12 @@ return Pkg.new {
                         ),
                         when(
                             os_dist.id == "centos" and platform.arch == "x64",
-                            coalesce(when(os_dist.version.major == 7, "verible-%s-CentOS-7.9.2009-Core-x86_64.tar.gz"))
+                            coalesce(
+                                when(
+                                    os_dist.version.major == 7,
+                                    _.format "verible-%s-CentOS-7.9.2009-Core-x86_64.tar.gz"
+                                )
+                            )
                         )
                     ),
                 }
```

**Comment by williamboman** [comment]
Cool! @nikhiljha could you verify that this still works on CentOS after my changes?

**Comment by nikhiljha** [comment]
@williamboman Yep! Just tested it on CentOS 7.9 and it works for me. Thanks! :)

**Pull request merged**
