### PR TITLE
feat(registry): add azure pipelines lsp

### LINKED ISSUE #1005: [New package]: azure-pipelines-language-server
### I've searched open & closed issues for similar requests

Yes

### Package name

azure-pipelines-language-server

### Package homepage

https://github.com/microsoft/azure-pipelines-language-server

### Languages

Adulterated yaml

### How is this package distributed?

Managed via Github
https://github.com/microsoft/azure-pipelines-language-server

### PR DESCRIPTION
**Pull request by treatybreaker**
Closes #1005

Currently able to start the with the in-built LSP client after installing like so:
```lua
local lsp_server_bin_dir = vim.fn.stdpath("data") .. "/mason/bin/"

vim.api.nvim_create_autocmd("FileType", {
    pattern = "yaml",
    desc = "Azure Pipelines Server Handler",
    callback = function()
        local client_id = vim.lsp.start({
            name = "Azure-Pipelines-LS",
            cmd = { lsp_server_bin_dir .. "azure-pipelines-language-server", "--stdio" },
            root_dir = vim.fn.getcwd(),
            capabilities = lsp_capabilities,
            on_attach = on_attach,
            settings = {
                yaml = {
                    schemas = {
                        ["https://raw.githubusercontent.com/microsoft/azure-pipelines-vscode/master/service-schema.json"] = {
                            "/azure-pipeline*.y*l",
                            "/*.azure",
                            "Azure-Pipelines/**/*.y*l",
                            "Pipelines/*.y*l",
                        },
                    },
                },
            },
        })

        if client_id then
            vim.lsp.buf_attach_client(0, client_id)
        end
    end,
})
```

As a note, Azure Pipelines LSP requires the file to be named `azure-pipelines.yml` by default, those settings I pass permit more filenames to be matched.

This language server is not included in [`nvim-lspconfig`](https://github.com/neovim/nvim-lspconfig) yet, I intend to start working over there to get it added.

GIF of the Language server in action:
out

### CODE REVIEW

**Comment by treatybreaker** [comment]
`nvim-lspconfig` had the LSP server renamed to `azure_pipelines_ls`, should I modify the name within `mason.nvim` to reflect that change as well?

**Comment by williamboman** [comment]
> `nvim-lspconfig` had the LSP server renamed to `azure_pipelines_ls`, should I modify the name within `mason.nvim` to reflect that change as well?

No that's fine. Mason doesn't track lspconfig names at all, it tracks upstream package names (in this case the npm package name would be the best candidate). 

I see they don't provide an executable, I don't think this is intentional (see for example https://github.com/microsoft/compose-language-service/issues/114). Let's first check if they're happy to add one!

**Comment by williamboman** [comment]
Created issue here https://github.com/microsoft/azure-pipelines-language-server/issues/145

**Comment by treatybreaker** [comment]
After poking around there seems to be a hanging PR in that repo since 2021 to add an executable output: https://github.com/microsoft/azure-pipelines-language-server/pull/107

If that hasn't been even interacted with since 2021 we're likely going to get no response on your issue :cry:. Hopefully we get some traction, but if there is no response what's the gameplan? I'd really like to be able to use Neovim with all of this integrated from Mason.

**Comment by williamboman** [comment]
> After poking around there seems to be a hanging PR in that repo since 2021 to add an executable output: [microsoft/azure-pipelines-language-server#107](https://github.com/microsoft/azure-pipelines-language-server/pull/107)
> 
> If that hasn't been even interacted with since 2021 we're likely going to get no response on your issue 😢. Hopefully we get some traction, but if there is no response what's the gameplan? I'd really like to be able to use Neovim with all of this integrated from Mason.

Seems like the author never signed the CLA, maybe that's why. It seems like they respond to issues fairly quickly, let's wait a while and see! For the time being you could run this branch locally, I guess?

**Comment by williamboman** [comment]
Hey sorry for the delay, been busy with getting https://github.com/mason-org/mason-registry live. Packages are no longer added to this registry, but instead to https://github.com/mason-org/mason-registry. I'll submit a PR to them to create an executable, after which I'll port this PR to the new registry

**Comment by williamboman** [comment]
Added in https://github.com/mason-org/mason-registry/pull/1015

**Pull request closed without merging**
