### PR TITLE
feat: add registry entry for black

### PR DESCRIPTION
**Pull request by mcauley-penney**
Thanks for this awesome plugin! Please let me know if there is something unsatisfactory about this PR.

### CODE REVIEW

**Review by williamboman — APPROVED** [review]
Cool, LGTM!

**Comment by mcauley-penney** [comment]
I busted stylua through null-ls earlier and missed some formatting by hand, that's my bad! Gonna reformat

**Comment by mcauley-penney** [comment]
@williamboman Sorry for the wait, I really dislike messy PRs and I'm trying to make this clean. It's flexing some of my git skills right now. 

I know what made the stylua check fail but I can't tell why the diff checker failed. I read the workflow but don't understand what the last actions in it are. What is it checking for?

**Comment by williamboman** [comment]
No worries at all! Those CI checks are somewhat draconian. The metadata job runs the scripts/autogen_metadata.sh script and ensures there are no diffs (to ensure the generated files are up to date). It might be falling because there was some new commits in the target branch, try merging with the `alpha` branch:

```
git remote add upstream ***@***.***:williamboman/mason.nvim
git fetch upstream
git merge upstream/alpha
```

**Comment by mcauley-penney** [comment]
I did a bunch of testing to try and figure out where things were going wrong. If the diff check fails, I will try the method you suggested. I frankly hate how messy this is, should have been a one-commit affair. Thank you for your patience.

**Comment by williamboman** [comment]
Thanks! I'll look into giving @williambotman another job to generate this automatically

**Comment by mcauley-penney** [comment]
No, thank you! You'd think I had never used git before with the way this went

**Pull request merged**
