### PR TITLE
feat(registry): add java-language-server

### LINKED ISSUE #388: [New package]: java_language_server
### Package name

java_language_server

### Package homepage

https://github.com/georgewfraser/java-language-server

### Languages

java

### How is this package distributed?

_No response_

### PR DESCRIPTION
**Pull request by vladaviedov**
Adding [java-language-server](https://github.com/georgewfraser/java-language-server)
Closes #388

### CODE REVIEW

**Review by williamboman — COMMENTED** [review]
Cool! A concern I have with this is that Windows install path makes use of shell scripts. Far from all Windows users have bash.exe installed on their system. Do you think they'd be able to provide a pre-built JAR file instead?

**Comment by vladaviedov** [comment]
It should be possible to get the pre-built version by extracting the vscode extension, but it also relies on a shell script to  start the program.

They do provide batch scripts for Windows though. Would `ctx.spawn.cmd` work?

**Comment by williamboman** [comment]
> It should be possible to get the pre-built version by extracting the vscode extension, but it also relies on a shell script to start the program.

I was trying to find if they publish the .vsix archive anywhere but couldn't find it. Not on GitHub or OpenVSX

**Comment by williamboman** [comment]
Closing this as packages are no longer added to this registry, see instead https://github.com/mason-org/mason-registry/.

**Comment by williamboman** [comment]
Added in https://github.com/mason-org/mason-registry/pull/1017

**Pull request closed without merging**
