### PR TITLE
feat: configurable registries

### PR DESCRIPTION
**Pull request by williamboman**

### CODE REVIEW

**Comment by A-Lamia** [comment]
I looked through and couldn't find anything but what is the code equivalent of this now ? `lrequire('mason-registry').get_package('codelldb'):get_install_path()`

**Comment by williamboman** [comment]
It's the same, if that's erroring you're probably setting up mason too late.

**Comment by A-Lamia** [comment]
yeah i thought that was the problem but now i don't think it is

**Comment by A-Lamia** [comment]
Yeah you are right was not loading in the correct order, sorry for the annoyance :D

**Comment by jcdickinson** [comment]
This is nuking 100% of my manual lsp configs, as I am using Mason only as a fallback when something isn't provided by nixpkgs/in the local env. Is that expected behavior?

**Pull request merged**
