### PR TITLE
feat(taplo): use prebuilt binary if available

### PR DESCRIPTION
**Pull request by williamboman**
I don't like this kind of mixing of installation sources, but I figured
this could be a good first experiment.

### CODE REVIEW

**Comment by williamboman** [comment]
Ping @zhang-stephen, this should be smoother now for Linux and Mac enjoyers

**Comment by zhang-stephen** [comment]
well, I don't think pre-built is necessary, I am just confused about the difference between nvim-lsp-installer and mason yesterday. 

and I noticed the author of taplo seems do not like to "release", so building taplo from latest master is a more reasonable choice.

So this PR is not necessary to be merged in my opinion... What do you think about it?

**Comment by zhang-stephen** [comment]
OK it's merged so quickly... 😂

**Comment by williamboman** [comment]
> and I noticed the author of taplo seems do not like to "release", so building taplo from latest master is a more reasonable choice.

`cargo install` doesn't build from HEAD anyway, it goes through crates.io

**Pull request merged**
